[platformio]
default_envs = heltec_wifi_lora_32_V3

[common]
platform  = espressif32 @ 6.4.0
framework = arduino

build_flags =
  -DCORE_DEBUG_LEVEL=5
  -DSLOW_CLK_TPYE=0
  -DLoRaWAN_DEBUG_LEVEL=3
  -DREGION_AS923
  -DACTIVE_REGION=LORAMAC_REGION_AS923
  -DLORAWAN_PREAMBLE_LENGTH=8
  -DLORAWAN_DEVEUI_AUTO=0 

lib_deps =
  heltecautomation/Heltec ESP32 Dev-Boards @ 2.1.1
  adafruit/Adafruit BusIO            @ ^1.17.0
  adafruit/Adafruit GFX Library      @ ^1.11.11
  adafruit/Adafruit SSD1306          @ ^2.5.7
  adafruit/Adafruit SHT31 Library
  mikalhart/TinyGPSPlus              @ ^1.0.3

monitor_speed = 115200
upload_speed  = 115200

[env:heltec_wifi_lora_32_V3]
extends = common
board   = heltec_wifi_lora_32_V3

build_flags =
  ${common.build_flags}
  -DHELTEC_BOARD=30
  -DHELTEC_WIFI_LORA_32_V3
  -DWIFI_LORA_32_V3
  -DMCU_ESP32_S3
  -DRADIO_CHIP_SX1262
  -DLORAWAN_OTAA_ENABLED=1          ; ← บังคับ OTAA ชัดเจน
  -DBOARD_IS_HELTEC_WIFI_LORA_32_V3